-- Run this in Supabase Dashboard → SQL Editor.
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null,
  semester text,
  category text not null default 'Other',
  description text,
  drive_url text not null,
  gplink_url text not null,
  created_at timestamptz not null default now()
);

alter table public.notes enable row level security;

drop policy if exists "Public can read notes" on public.notes;
create policy "Public can read notes"
on public.notes for select
to anon, authenticated
using (true);

drop policy if exists "Admins can insert notes" on public.notes;
create policy "Admins can insert notes"
on public.notes for insert
to authenticated
with check (true);

drop policy if exists "Admins can update notes" on public.notes;
create policy "Admins can update notes"
on public.notes for update
to authenticated
using (true)
with check (true);

drop policy if exists "Admins can delete notes" on public.notes;
create policy "Admins can delete notes"
on public.notes for delete
to authenticated
using (true);

-- IMPORTANT:
-- This starter uses any authenticated Supabase user as an admin.
-- For a single-admin production site, keep the Supabase project private
-- and create only your own admin account. For stronger role-based security,
-- add a profiles/roles table and tighten the policies before inviting users.
